### ISSUE TITLE
In Windows the clipboard content is lost if "exit" or "raise" is called

### ISSUE THREAD

**Issue by bdimych** [ryanmelt/qtbindings#102]
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [i386-mingw32]

C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>gem install qtbindings
Fetching: qtbindings-qt-4.8.6-x86-mingw32.gem (100%)
Successfully installed qtbindings-qt-4.8.6-x86-mingw32
Fetching: qtbindings-4.8.6.0-x86-mingw32.gem (100%)
Successfully installed qtbindings-4.8.6.0-x86-mingw32
Parsing documentation for qtbindings-4.8.6.0-x86-mingw32
Installing ri documentation for qtbindings-4.8.6.0-x86-mingw32
Parsing documentation for qtbindings-qt-4.8.6-x86-mingw32
Installing ri documentation for qtbindings-qt-4.8.6-x86-mingw32
Done installing documentation for qtbindings, qtbindings-qt after 4 seconds
2 gems installed

C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>type bug-ruby-qtbindings-exception-empty-clipboard.rb
#!c:\Ruby21\bin\ruby.exe -w

require 'Qt'

app = Qt::Application.new ARGV

top = Qt::Widget.new
lyo = Qt::VBoxLayout.new
top.setLayout lyo

te = Qt::TextEdit.new
te.setText "copy this text then press the button\nexception is raised and clipboard becomes empty\n"
lyo.addWidget te

pb = Qt::PushButton.new 'ok'
pb.connect(SIGNAL :clicked) {
  raise 'my exception'
}
lyo.addWidget pb

top.show
app.exec

C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>ruby bug-ruby-qtbindings-exception-empty-clipboard.rb
bug-ruby-qtbindings-exception-empty-clipboard.rb:17:in `block in <main>': my exception (RuntimeError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:2454:in `call'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:2454:in `invoke'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479:in `qt_metacall'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479:in `method_missing'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479:in `exec'
        from bug-ruby-qtbindings-exception-empty-clipboard.rb:22:in `<main>'
pure virtual method called
terminate called without an active exception

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>
C:\Users\bdimych>

**Comment by ryanmelt** [comment]
I believe this is a qt issue, not qtbindings.    See: http://stackoverflow.com/questions/2007103/how-can-i-disable-clear-of-clipboard-on-exit-of-pyqt4-application
