### ISSUE TITLE
Won't compile with cmake 3.1

### ISSUE THREAD

**Issue by froderik** [ryanmelt/qtbindings#106]
On arch linux, ruby 2.1.5 and cmake 3.1.0 I get:

```
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:112 (elseif):
  given arguments:

    "VERSION_LESS" "3.1"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:501 (_pkgconfig_parse_options)
  /usr/share/cmake-3.1/Modules/FindOpenSSL.cmake:41 (pkg_check_modules)
  cmake/modules/Qt4ConfigDependentSettings.cmake:224 (FIND_PACKAGE)
  cmake/modules/FindQt4.cmake:1233 (INCLUDE)
  CMakeLists.txt:16 (FIND_PACKAGE)
```

among other messages..... Downgrading to cmake 3.0.2 solves the problem.

**Comment by froderik** [comment]
Not sure what to do with this. If some points me in a good direction I can give it a try.

**Comment by DexterLB** [comment]
Confirmed with cmake 3.1.1

**Comment by MaximeMorel** [comment]
Try setting CMAKE_MINIMUM_REQUIRED_VERSION to something.
For example:
cmake -DCMAKE_MINIMUM_REQUIRED_VERSION=3.0 path_to_source

**Comment by nilsding** [comment]
@MaximeMorel It works now!

I changed line 203 in `extconf.rb` to `file.puts "cmake -DCMAKE_MINIMUM_REQUIRED_VERSION=3.0 \\"`.  On Windows systems, you'd have to change line 82 instead.

**Comment by froderik** [comment]
Newer versions of cmake solves the problem. I have succesfully used both cmake 3.1.1 and 3.1.2.
