### ISSUE TITLE
Issue #106 is still alive: wont compile with cmake 3.1.2

### ISSUE THREAD

**Issue by nedab** [ryanmelt/qtbindings#111]
just trying to compile it, and it breaks with cmake

**Comment by nedab** [comment]
My release was just being updated, still this error:

"CMake Error at /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:112 (elseif):
  given arguments:

    "VERSION_LESS" "3.1"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake-3.1/Modules/FindPkgConfig.cmake:501 (_pkgconfig_parse_options)
  /usr/share/cmake-3.1/Modules/FindOpenSSL.cmake:41 (pkg_check_modules)
  cmake/modules/Qt4ConfigDependentSettings.cmake:224 (FIND_PACKAGE)
  cmake/modules/FindQt4.cmake:1233 (INCLUDE)
  CMakeLists.txt:16 (FIND_PACKAGE)"

**Comment by ryanatball** [comment]
I added CMAKE_MINIMUM_REQUIRED_VERSION=2.6 to the build.  Please let me know if that doesn't resolve your issue.  Thanks!  #106

**Comment by sroycode** [comment]
Try this:

1. COPY these two files into your cmake_modules folder
https://github.com/sroycode/rpcz/blob/master/cmake_modules/FindPkgConfig.cmake
https://github.com/sroycode/rpcz/blob/master/cmake_modules/FindPackageHandleStandardArgs.cmake

2. Update the include/zmq.hpp ( to handle zmq4) by 
https://github.com/sroycode/rpcz/blob/master/include/zmq.hpp
