### ISSUE TITLE
Qt::Sound finished? always returning false

### ISSUE THREAD

**Issue by Pluto1010** [ryanmelt/qtbindings#125]
Hi!

I'm trying to use Qt 4.8.6 with ruby 2.2.0 and Mac OSX 10.10.3

My super-simple code looks like:
```
require 'Qt'
sound = Qt::Sound.new "sample.m4a"
sound.play

until sound.finished? do
    puts sound.finished?
    sleep 1
end
```

The sound sample is playing and it returns false during that playback. But it never switches to true. Even after the sample ended.

Can you help?

**Comment by jmthomas** [comment]
It seems like the Qt::Sound API is rather primitive and limited. On Windows for example it says that the isFinished routine always returns true for unlooped sounds (http://doc.qt.io/qt-4.8/qsound.html#isFinished). I even found that setting the loop count to 1 wasn't enough on Windows. I had to set it to 2 and then break the loop when the count become 1.
```
require 'Qt'
sound = Qt::Sound.new("8kmp38.wav")
sound.setLoops(2)
sound.play()
while (sound.loopsRemaining != 1)
  sleep 0.1
  puts "remaining:#{sound.loopsRemaining} finished:#{sound.isFinished}"
end
puts sound.isFinished
```
