### ISSUE TITLE
Support for Qt 5 planned?

### ISSUE THREAD

**Issue by brandondrew** [ryanmelt/qtbindings#133]
The README *sort of* leaves open the possibility that Qt 5 is currently supported, since

> starting at qtbindings version 4.8.6.0

might be interpreted as meaning that 4.8.5.0 *and up* are supported, with "and up" meaning including 5.  But it seems more likely that this is not the intended meaning.  In either case, it would be helpful to have an explicit mention of if 5 is supported currently, and if there are plans to support it in the future.

**Comment by jmthomas** [comment]
I added an explicit note that Qt 5 is not supported.

**Comment by brandondrew** [comment]
Thank you

-- 
Brandon Zylstra
616-916-4511
