### ISSUE TITLE
Can not compile it

### ISSUE THREAD

**Issue by shevegen** [ryanmelt/qtbindings#137]
Hello. If this compile-bug is known or a user error, feel free to close it down.

My system:

==================================================================

    Operating System:        GNU/Linux
    OS Bit Type:             x86_64
    CPU Model:               Intel(R) Celeron(R) CPU G1630 @ 2.80GHz, 2 cores
    CFLAGS in use:           -O2 -fPIC -fno-strict-overflow -Wno-error
    RAM:                     7858728 kB RAM (7674.5 MB) (7.5 Gig)
    GCC Version:             5.3.0
    Glibc Version:           2.22
    Kernel Version:          4.4.0
    Ruby Version:            2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
    Rubygems Version:        2.6.1
    Qt: 4.8.7
    KDE Development Platform: 4.14.14
    kde4-config: 1.0
    4.14.14
    The prefix for KDE4 is at /usr

==================================================================

---

Scanning dependencies of target smokeqthelp
make[3]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
make[3]: Entering directory '/Depot/Downloads/qtbindings-master/ext/build'
[ 78%] Building CXX object smoke/qthelp/CMakeFiles/smokeqthelp.dir/smokedata.o
[ 79%] Building CXX object smoke/qthelp/CMakeFiles/smokeqthelp.dir/x_1.o
[ 79%] Linking CXX shared library libsmokeqthelp.so
make[3]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
[ 79%] Built target smokeqthelp
make[3]: Entering directory '/Depot/Downloads/qtbindings-master/ext/build'
Scanning dependencies of target qtruby4shared
make[3]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
make[3]: Entering directory '/Depot/Downloads/qtbindings-master/ext/build'
[ 80%] Building CXX object ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/Qt.o
[ 81%] Building CXX object ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/handlers.o
[ 81%] Building CXX object ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/marshall_types.o
In file included from /Programs/Ruby/2.3.0/include/ruby-2.3.0/ruby.h:33:0,
                 from /Depot/Downloads/qtbindings-master/ext/ruby/qtruby/src/marshall.h:14,
                 from /Depot/Downloads/qtbindings-master/ext/ruby/qtruby/src/marshall_types.h:28,
                 from /Depot/Downloads/qtbindings-master/ext/ruby/qtruby/src/marshall_types.cpp:19:
/Depot/Downloads/qtbindings-master/ext/ruby/qtruby/src/marshall_types.cpp: In function 'void show_exception_message()':
/Programs/Ruby/2.3.0/include/ruby-2.3.0/ruby/ruby.h:882:52: error: '__builtin_choose_expr' was not declared in this scope
      OBJ_WB_UNPROTECT((VALUE)(obj)), ((VALUE)(obj))))
                                                    ^
/Programs/Ruby/2.3.0/include/ruby-2.3.0/ruby/ruby.h:1039:48: note: in definition of macro 'RARRAY_CONST_PTR'
 #define RARRAY_CONST_PTR(a) rb_array_const_ptr(a)
                                                ^
/Programs/Ruby/2.3.0/include/ruby-2.3.0/ruby/ruby.h:1059:50: note: in expansion of macro 'RB_OBJ_WB_UNPROTECT_FOR'
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                                  ^
/Depot/Downloads/qtbindings-master/ext/ruby/qtruby/src/marshall_types.cpp:82:21: note: in expansion of macro 'RARRAY_PTR'
     VALUE message = RARRAY_PTR(bt)[0];
                     ^
ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/build.make:110: recipe for target 'ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/marshall_types.o' failed
make[3]: *** [ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/marshall_types.o] Error 1
make[3]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
CMakeFiles/Makefile2:1639: recipe for target 'ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/all' failed
make[2]: *** [ruby/qtruby/src/CMakeFiles/qtruby4shared.dir/all] Error 2
make[2]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/Depot/Downloads/qtbindings-master/ext/build'
Makefile:47: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by jmthomas** [comment]
We currently can't compile against Ruby 2.3.0 due to a known issue. See #134.
