### ISSUE TITLE
Drag and drop issue on OS X 10.11.1 with Qt 4.8.7

### ISSUE THREAD

**Issue by berpj** [ryanmelt/qtbindings#138]
I'm using the `draganddrop/dropsite` example.

Environment:
OS X 10.11.1
Qt 4.8.7_2
Ruby 2.3.0
qtbindings 4.8

Problem: if I try to print the path to the dropped file by adding `p event.mimeData().urls[0].toLocalFile()` in the `dropEvent` method, I get something like that `"/.file/id=6571367.11958400"`.

It looks like it's a problem with Qt 4 on OS X. Is there a way to fix this / a workaround?

Thanks

**Comment by jmthomas** [comment]
I haven't done much development on OS X with qtbindings and have never implemented drag and drop. Does the file ID vary for each file? Do you think it's a real file handle? Perhaps there's some method to translate back to a file path. Google around for something and let us know what you find.
