### ISSUE TITLE
ruby 2.3

### ISSUE THREAD

**Issue by mikecanann** [ryanmelt/qtbindings#139]
Does the project have support for ruby version 2.3?

C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.3/qtruby4 (LoadError)

I can see in the lib directory there is a 2.0, 2.1 and a 2.2. But no 2.3.

**Comment by ryanmelt** [comment]
The Windows gem currently only supports up to 2.2.   I'll release an update for windows once a RubyInstaller for version 2.3.1 is available.  (There is a known bug in 2.3.0 that keeps qtbindings from compiling on all platforms).

**Comment by maca89** [comment]
Hi, Ruby 2.3.1 is out. When can we expect a new release of qtbindings?

**Comment by ryanatball** [comment]
Working on it now.  Hopefully next week.

**Comment by maca89** [comment]
Thanks!
