### ISSUE TITLE
require 'Qt' failing

### ISSUE THREAD

**Issue by shevegen** [ryanmelt/qtbindings#143]
require 'Qt'

`LoadError: cannot load such file -- 2.3/qtruby4`

I am not sure why 2.3/ is prefaced there. Also not sure why it attempts to require a file called qtruby4.

My system:

=============================================================
 
   Operating System:       GNU/Linux
    OS Bit Type:            x86_64
    CPU Model:              Intel(R) Celeron(R) CPU G1630 @ 2.80GHz, 2 cores
    CFLAGS in use:          -O2 -fPIC -fno-strict-overflow -Wno-error
    RAM:                    7858728 kB RAM (7674.5 MB) (7.5 Gig)
    Screen Resolution:      1920x1080
    GCC Version:            5.3.0
    Glibc Version:          2.22
    Kernel Version:         4.4.0
    Ruby Version:           2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    Rubygems Version:       2.6.4

=============================================================

**Comment by jmthomas** [comment]
2.3.1 is not supported yet, see #139
