### ISSUE TITLE
In the README Qt install

### ISSUE THREAD

**Issue by DouglasAllen** [ryanmelt/qtbindings#149]
site = https://download.qt.io/official_releases/qt/4.8/4.8.6/

which one would you recommend for windows? I have a hunch it's mingw32 but your batchfile has all kinds of options. Since this is all you support then I need focus and what to use in the batchfile.
I've commented out a lot in there and already cloned twice since I think I messed up the first one with all kinds of builds that I didn't know what to get rid of.
I'm going to try mingw32 because I have that also installed in the devkit.

**Comment by ryanatball** [comment]
Hi Doug,

With the most recent release of qtbindings I actually recompile Qt with the Ruby Devkit to maximize compatibility.   If  you look in the vendor folder there are BuildQt4Win32.bat and BuildQt4Win64.bat.  Those are the bat files I use to build.  They should be placed in the Qt/4.8.6 root folder.

Also, yes I do recommend version 4.8.6.   Version 4.8.7 doesn't work with qtbindings yet for some reason and I haven't had a chance to debug.

Also, I assume you already know, but you shouldn't need to compile any of this on windows.  You can just install the binary gem.   (gem install qtbindings)

Good luck.
Ryan

**Comment by DouglasAllen** [comment]
Wow! Do the examples come with the gem install version?
I was just looking for something like the old Korundum and qt4ruby so I'll see how this goes. Thanks!

**Comment by ryanatball** [comment]
The examples are bundled into the gem folder.   You can also run them from a git checkout after installing the gem.

**Comment by DouglasAllen** [comment]
Great thanks. I'm running some examples and I notice that my rubocop linter for vscode finds that a lot of the initialize methods are too long. Would you want to see some of my changes if I create a new branch and make a pull request? I'm only up to tutorial t7.rb

**Comment by ryanatball** [comment]
I'm not really interested in refactoring the examples.  I think most of them are fairly straight ports of the C++ versions.  Bug fixes and overall improvements are always welcome though.

**Comment by DouglasAllen** [comment]
Of course and I can tell they're not very rubyistic. They could use some work but for the most part they work. I'm going to put them in my fork though some stop on by and have a look when you get a chance.

**Comment by jmthomas** [comment]
I for one hate all the tabs and bad formatting in the examples. If you get them all running successfully send a pull request. I've never actually run through the tutorial so let us know how that goes.
