### ISSUE TITLE
Build failing in macOS 10.13

### ISSUE THREAD

**Issue by glenfarclas17** [ryanmelt/qtbindings#150]
Hi All,

My first attempts at building qtbindings 4.8.6.3 in macOS 10.13 failed with the error 
     `ordered comparison between pointer and zero ('void *' and 'int')`
at line 2211 of ext/ruby/qtruby/src/qtruby.cpp

Not being a C++ programmer,  I searched around the web a bit and ended up changing that line from:
    `	return (ptr > 0 ? Qtrue : Qfalse);`
to: 
    `	return (ptr > (void*)0 ? Qtrue : Qfalse);`
which seems to have fixed the issue, the build succeeded and my apps seem to work fine so far.

Cheers,
-Chris

**Comment by silver926z** [comment]
Hi,

I failed with the error same as you
After I change `ext/ruby/qtruby/src/qtruby.cpp`  file and run `gem install qtbindings`,
it continued fail with same issue and my file seems back to 
`return (ptr > 0 ? Qtrue : Qfalse);`

Is there a way gem install using the qtruby.cpp I changed ?

thanks.

**Comment by silver926z** [comment]
Sorry, I am new to ruby

I downloaded gem file `gem unpck` -> edit -> `gem build` 
and it works fine

Thanks

**Comment by ryanatball** [comment]
Fixed with qtbindings 4.8.6.4
