### ISSUE TITLE
incompatible library version

### ISSUE THREAD

**Issue by paradoxon82** [ryanmelt/qtbindings#154]
Hi,

I successfully installed the qtbindings gem version 4.8.6.2
I linked it agains some Qt version 4.8.6.x
Now, I get the following error on "require 'Qt'"

incompatible library version

Is this due to having not linked against the correct Qt library version. Or is it another reason?

**Comment by paradoxon82** [comment]
Additional info:
OS: centos6
ruby: 2.5 compiled myself

**Comment by ryanatball** [comment]
You should use the latest gem (4.8.6.4).   Ruby must be compiled/configured with --enable-shared or it will not work with qtbindings (this is probably your problem).   We have not done any testing yet with Ruby 2.5, but that is probably not the problem on linux.

**Comment by paradoxon82** [comment]
thanks, --enable-shared fixed the issue
