### ISSUE TITLE
Qt4 Deprecation

### ISSUE THREAD

**Issue by heliochronix** [ryanmelt/qtbindings#168]
Hello,

I know that there have been a couple previous issues opened (and closed) regarding updating to Qt5, but perhaps it is time to re-address this issue.

Qt4's end-of-life was in 2015, and now many popular distributions have or will soon officially dropped Qt4 from their repositories. For example, Ubuntu 20.04, CentOS 8, and Arch have all removed Qt4 support, and Debian sid has removed it in preparation for their next release as shown [here](https://wiki.debian.org/Qt4Removal). Many of them cite the difficulties in maintaining the package due to incompatibilities with modern systems. As such, it is growing increasingly difficult to use software like COSMOS on any current linux distribution.

Most everything else in COSMOS builds fine on a modern system, and it seems qtbindings is the one component holding it back at this point. Perhaps we can reconsider support for Qt5 now?

**Comment by ryanatball** [comment]
I'm well aware of the death of qt4.  I've estimated the effort to get qtbindings to work with Qt5 to be at least 2 months of full time work.  For that reason, and others, mainly that everyone wants "cloud" support now, COSMOS is moving to a web based interface.   Unless I get some help, Qt5 isn't going to happen anytime soon.

**Comment by heliochronix** [comment]
Hello,

My apologies, I did not realize COSMOS was going that direction. Thank you
for clarifying! Is the development of the web based version being done on
the COSMOS repository? That actually sounds pretty nice.

**Comment by ryanatball** [comment]
We've moved primary development internal for various reasons, but COSMOS 5 will still be open sourced.  I haven't posted an announcement about this yet on the website and probably should.   We're just over 2 months into the changeover and it is going very well.   I'll hopefully post a beta version in about 3 months.

**Comment by heliochronix** [comment]
That's really good news! May I ask if the backend will still be similar to
the existing system? That is, if I continue development on interfaces and
configurations for a headless implement of the current COSMOS version and
DART and such, will that easily convert over to the new version?

**Comment by ryanatball** [comment]
Configuration of the backend will be very similar.  Interfaces/protocols should be essentially unchanged.  Packet definitions will be essentially unchanged.  Screens will be essentially unchanged. 
The scripting api will be essentially unchanged. 

DART I'm less sure about.  It may end up being replaced by a similar but different API to retrieve historical data.

**Comment by heliochronix** [comment]
Thanks for the clarification! Looking forward to hearing more about COSMOS
5 when it goes public.
