### ISSUE TITLE
Add jpg support for Qt::Pixmap on Windows

### ISSUE THREAD

**Issue by stomar** [ryanmelt/qtbindings#32]
Creating a QPixmap with a jpg file does not work on Windows and results
in a null pixmap (on Linux it works just fine).

``` ruby
require 'Qt'
app = Qt::Application.new ARGV
Qt::Widget.new do
  pixmap = Qt::Image.new 'test.jpg'
  puts 'Null Pixmap'  if pixmap.null?  # => Null Pixmap
  puts Qt::ImageReader.supported_image_formats  # => bmp, pbm, pgm, png, ppm, xbm, xpm
end
```

System:
- Windows XP Professional
- Ruby 1.9.3-p125
- qtbindings 4.6.3.4 x86-mingw32

**Comment by rubimazaki** [comment]
Still not working, even after hardcoding the plugin path... JPEG SHOULD BE OUT OF THE BOX. No... plugins.. . these are known to be a pain in the ass! (for example: "windows plugin"... ahhhh)
