### ISSUE TITLE
Error gem installing qtbindings

### ISSUE THREAD

**Issue by joshvoigts** [ryanmelt/qtbindings#45]
I'm getting an error on Mac OS X 10.6.8 gem installing qtbindings. Here's a gist: https://gist.github.com/4171016

Ruby is 1.9.3p194

Qt 4.8.3 is installed:

```
~  > brew info qt
qt: stable 4.8.3 (bottled), HEAD
http://qt.nokia.com/
/usr/local/Cellar/qt/4.8.3 (2778 files, 197M) *
https://github.com/mxcl/homebrew/commits/master/Library/Formula/qt.rb
==> Options
--with-mysql
    Enable MySQL plugin
--universal
    Build a universal binary
--with-qt3support
    Enable deprecated Qt3Support module
--with-debug-and-release
    Compile Qt in debug and release mode
--with-qtdbus
    Enable QtDBus module
--developer
    Compile and link Qt with developer options
--with-demos-examples
    Enable Qt demos and examples
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.
```

**Comment by blutsvente** [comment]
I have the same problem as @edgurgel using the latest qtbindings, but with 
- OSX 10.9.5 (XCode 6.2)
- Ruby 2.2.1(installed with rvm and switches --with-gcc=clang --enable-shared)
- cmake 3.5.0 
- QT 4.8.7.
I could not find QT 4.8.7_1 which was successful for somebody in #128. Maybe somebody can point me to it!?
