### ISSUE TITLE
QSqlRelationalDelegate has private copy constructor - missing entries in smokeconfig.xml

### ISSUE THREAD

**Issue by D-Alex** [ryanmelt/qtbindings#53]
On Mac OS 10.8.3 with Qt 4.8.4 and ruby 1.9.3 building the gem results in the error message: QSqlRelationalDelegate has private copy constructor. 

The reason is that smoke generates wrappers for private copy constructors. To solve this problem the following lines must be added to qtwebkit/smokeconfig.xml and qtsql/smokeconfig.xml

qtsql/smokeconfig.xml

```
<exclude>
    <signature>.*QSqlRelationalDelegate::QSqlRelationalDelegate\(const QSqlRelationalDelegate&amp;\).*</signature>
</exclude>
```

qtwebkit/smokeconfig.xml:

```
<exclude>
    <signature>.*QGraphicsWebView::QGraphicsWebView\(const QGraphicsWebView&amp;\).*</signature>
    <signature>.*QWebInspector::QWebInspector\(const QWebInspector&amp;\).*</signature>
    <signature>.*QWebView::QWebView\(const QWebView&amp;\).*</signature>
</exclude>
```

**Comment by blutsvente** [comment]
For the amateurs among us, it should be noted that after modifying the .xml files one should not call gem install again but directly call "make" in the qtbindings dir (see gem help install).
