### ISSUE TITLE
Question: Qt 5.x

### ISSUE THREAD

**Issue by kybu** [ryanmelt/qtbindings#94]
Hi,

Is there any plan supporting Qt 5? Thanks.

Peter

**Comment by jamesst20** [comment]
Hi,

@ryanmelt Have you changed your mind ? Are you planning to support Qt 5 ?

**Comment by mrmarbury** [comment]
Hi,

I would love to see Qt5 as well. It is out and stable for quite a while now.

Cheers,
Stefan
