### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by shevegen** [ryanmelt/qtbindings#97]
cmake \
-G "Unix Makefiles" \
-Wno-dev \
-DRUBY_EXECUTABLE=/Programs/Ruby/2.1.3/bin/ruby \
..
-- The C compiler identification is GNU 4.7.3
-- The CXX compiler identification is GNU 4.7.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake (found version "4.8.6") 
-- Found Qt-Version 4.8.6 (using /usr/bin/qmake)
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- looking for config.h
-- --------FindRuby.cmake debug------------
-- _RUBY_POSSIBLE_EXECUTABLE_NAMES: ruby;ruby1.9;ruby19;ruby1.9.1;ruby191;ruby1.9.2;ruby192;ruby1.8;ruby18
-- _RUBY_POSSIBLE_LIB_NAMES: ruby;ruby;ruby-static;ruby2.1;ruby21;ruby-2.1.0
-- RUBY_ARCH_DIR: /Programs/Ruby/2.1.3/lib/ruby/2.1.0/i686-linux
-- RUBY_HDR_DIR: /Programs/Ruby/2.1.3/include/ruby-2.1.0
-- RUBY_POSSIBLE_LIB_DIR: 
-- Found RUBY_VERSION: "2.1.0" , short: "2.1", nodot: "21"
-- _RUBY_REQUIRED_VARS: RUBY_EXECUTABLE;RUBY_INCLUDE_DIR;RUBY_LIBRARY;RUBY_CONFIG_INCLUDE_DIR
-- --------------------
-- Found Ruby: /Programs/Ruby/2.1.3/bin/ruby  
-- Found OpenGL: /usr/lib/libGL.so  
-- Checking how Qt was built...
-- Threshold is set to 10
-- QT_NO_DEBUG *Undefined*
-- QT_NO_ACCESSIBILITY *Undefined*
-- QT_NO_BUTTONGROUP *Undefined*
-- QT_NO_COLORDIALOG *Undefined*
-- QT_NO_DATETIMEEDIT *Undefined*
-- QT_NO_DIALOG *Undefined*
-- QT_NO_ERRORMESSAGE *Undefined*
-- QT_NO_FILEDIALOG *Undefined*
-- QT_NO_FONTDIALOG *Undefined*
-- QT_NO_GROUPBOX *Undefined*
-- QT_NO_LCDNUMBER *Undefined*
-- QT_NO_LINEEDIT *Undefined*
-- QT_NO_LISTVIEW *Undefined*
-- QT_NO_MAINWINDOW *Undefined*
-- QT_NO_MENUBAR *Undefined*
-- QT_NO_MESSAGEBOX *Undefined*
-- QT_NO_PRINTDIALOG *Undefined*
-- QT_NO_PROGRESSBAR *Undefined*
-- QT_NO_PROGRESSDIALOG *Undefined*
-- QT_NO_PUSHBUTTON *Undefined*
-- QT_NO_RADIOBUTTON *Undefined*
-- QT_NO_SCROLLBAR *Undefined*
-- QT_NO_SLIDER *Undefined*
-- QT_NO_STYLE_PLASTIQUE *Undefined*
-- QT_NO_STYLE_WINDOWSXP [Defined]
-- QT_NO_STYLE_WINDOWS *Undefined*
-- QT_NO_STYLE_MAC [Defined]
-- QT_NO_STYLE_CLEANLOOKS *Undefined*
-- QT_NO_TABLEVIEW *Undefined*
-- QT_NO_TEXTBROWSER *Undefined*
-- QT_NO_TEXTEDIT *Undefined*
-- QT_NO_TOOLBUTTON *Undefined*
-- Found Qt-Version 4.8.6 (using /usr/bin/qmake)
-- Found Qt-Version 4.8.6 (using /usr/bin/qmake)
-- Build SMOKE bindings: QtDBus;QtDeclarative;QtGui;QtHelp;QtMultimedia;QtNetwork;QtOpenGL;QtScript;QtSql;QtSvg;QtTest;QtUiTools;QtWebKit;QtXml;QtXmlPatterns
-- Skip SMOKE bindings: 
-- looking for config.h
-- --------FindRuby.cmake debug------------
-- _RUBY_POSSIBLE_EXECUTABLE_NAMES: ruby;ruby1.9;ruby19;ruby1.9.1;ruby191;ruby1.9.2;ruby192;ruby1.8;ruby18
-- _RUBY_POSSIBLE_LIB_NAMES: ruby;ruby;ruby-static;ruby2.1;ruby21;ruby-2.1.0
-- RUBY_ARCH_DIR: /Programs/Ruby/2.1.3/lib/ruby/2.1.0/i686-linux
-- RUBY_HDR_DIR: /Programs/Ruby/2.1.3/include/ruby-2.1.0
-- RUBY_POSSIBLE_LIB_DIR: 
-- Found RUBY_VERSION: "2.1.0" , short: "2.1", nodot: "21"
-- _RUBY_REQUIRED_VARS: RUBY_EXECUTABLE;RUBY_INCLUDE_DIR;RUBY_LIBRARY;RUBY_CONFIG_INCLUDE_DIR
-- --------------------
-- Performing Test RubyCompiles
-- Performing Test RubyCompiles - Success
-- Ruby Executable: /Programs/Ruby/2.1.3/bin/ruby
-- Ruby Libraries: /usr/lib/libruby.so
-- Ruby Include Directories: /Programs/Ruby/2.1.3/include/ruby-2.1.0/Programs/Ruby/2.1.3/include/ruby-2.1.0/i686-linux
-- Build Ruby bindings: QtDeclarative;QtRuby;QtScript;QtTest;QtUiTools;QtWebKit
-- Skip Ruby bindings: 
-- Configuring done
-- Generating done
-- Build files have been written to: /Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build
cd ext/build; make
make[1]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[2]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Scanning dependencies of target cppparser
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[  0%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/ast.o
[  1%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/default_visitor.o
[  1%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/memorypool.o
[  2%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/visitor.o
[  3%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/control.o
[  3%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/lexer.o
[  4%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/parser.o
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/generator/parser/parser.cpp:1035:2: warning: #warning "implement me" [-Wcpp]
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/generator/parser/parser.cpp:2603:2: warning: #warning "implemente me (AST)" [-Wcpp]
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/generator/parser/parser.cpp:3489:2: warning: #warning "mark the ast as constant" [-Wcpp]
[  5%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/listnode.o
[  5%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/tokens.o
[  6%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/dumptree.o
[  6%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/parsesession.o
[  7%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/commentparser.o
[  8%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/commentformatter.o
[  8%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/codegenerator.o
[  9%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/indexedstring.o
[ 10%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/stringhelpers.o
[ 10%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-stream.o
[ 11%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-macro-expander.o
[ 12%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-scanner.o
[ 12%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-macro.o
[ 13%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-engine.o
[ 13%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-internal.o
[ 14%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-environment.o
[ 15%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/pp-location.o
[ 15%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/preprocessor.o
[ 16%] Building CXX object generator/parser/CMakeFiles/cppparser.dir/rpp/chartools.o
Linking CXX shared library ../bin/libcppparser.so
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 16%] Built target cppparser
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Scanning dependencies of target smokegen
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 17%] Building CXX object generator/CMakeFiles/smokegen.dir/main.o
[ 17%] Building CXX object generator/CMakeFiles/smokegen.dir/generatorenvironment.o
[ 18%] Building CXX object generator/CMakeFiles/smokegen.dir/generatorvisitor.o
[ 19%] Building CXX object generator/CMakeFiles/smokegen.dir/generatorpreprocessor.o
[ 19%] Building CXX object generator/CMakeFiles/smokegen.dir/options.o
[ 20%] Building CXX object generator/CMakeFiles/smokegen.dir/type_compiler.o
[ 20%] Building CXX object generator/CMakeFiles/smokegen.dir/name_compiler.o
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/generator/name_compiler.cpp:139:2: warning: #warning "NameCompiler::visitUnqualifiedName() -- implement me" [-Wcpp]
[ 21%] Building CXX object generator/CMakeFiles/smokegen.dir/type.o
Linking CXX executable bin/smokegen
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 21%] Built target smokegen
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Scanning dependencies of target generator_smoke
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 21%] Building CXX object generator/generators/smoke/CMakeFiles/generator_smoke.dir/generator_smoke.o
[ 22%] Building CXX object generator/generators/smoke/CMakeFiles/generator_smoke.dir/writeClasses.o
[ 22%] Building CXX object generator/generators/smoke/CMakeFiles/generator_smoke.dir/writeSmokeDataFile.o
[ 23%] Building CXX object generator/generators/smoke/CMakeFiles/generator_smoke.dir/helpers.o
Linking CXX shared module ../../bin/generator_smoke.so
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 23%] Built target generator_smoke
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Scanning dependencies of target generator_dump
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 24%] Building CXX object generator/generators/dump/CMakeFiles/generator_dump.dir/generator_dump.o
Linking CXX shared module ../../bin/generator_dump.so
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 24%] Built target generator_dump
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Scanning dependencies of target smokebase
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 24%] Building CXX object smoke/smokebase/CMakeFiles/smokebase.dir/smokebase.o
Linking CXX shared library libsmokebase.so
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 24%] Built target smokebase
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 25%] Generating smokedata.cpp, x_1.cpp, x_2.cpp, x_3.cpp, x_4.cpp, x_5.cpp, x_6.cpp, x_7.cpp, x_8.cpp, x_9.cpp, x_10.cpp, x_11.cpp, x_12.cpp, x_13.cpp, x_14.cpp, x_15.cpp, x_16.cpp, x_17.cpp, x_18.cpp, x_19.cpp, x_20.cpp
using generator "/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build/generator/bin/generator_smoke.so" 
parsing "/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/smoke/qtcore/qtcore_includes.h" 
Generating SMOKE sources... 
preparing SMOKE data [qtcore]
writing out smokedata.cpp [qtcore]
writing out x_*.cpp [qtcore]
Done. 
Scanning dependencies of target smokeqtcore
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
make[3]: Entering directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
[ 25%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/smokedata.o
[ 26%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_1.o
[ 27%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_2.o
[ 27%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_3.o
[ 28%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_4.o
[ 29%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_5.o
[ 29%] Building CXX object smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_6.o
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build/smoke/qtcore/x_6.cpp: In static member function 'static void __smokeqtcore::x_QEvent::x_173(Smoke::Stack)':
/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build/smoke/qtcore/x_6.cpp:1891:29: error: 'PlatformPanel' is not a member of 'QEvent'
smoke/qtcore/CMakeFiles/smokeqtcore.dir/build.make:239: recipe for target 'smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_6.o' failed
make[3]: *** [smoke/qtcore/CMakeFiles/smokeqtcore.dir/x_6.o] Error 1
make[3]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
CMakeFiles/Makefile2:419: recipe for target 'smoke/qtcore/CMakeFiles/smokeqtcore.dir/all' failed
make[2]: *** [smoke/qtcore/CMakeFiles/smokeqtcore.dir/all] Error 2
make[2]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Makefile:117: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.0/ext/build'
Makefile:47: recipe for target 'build' failed
make: *** [build] Error 2

make failed, exit code 2

My system:

Operating System:      GNU/Linux
OS Bit Type:           i686
Kernel Version:        3.2.29
GCC Version:           4.7.3 
Glibc Version:         2.15
CFLAGS in use:         -O2 -fPIC -fno-strict-overflow
RAM:                   7893124 kB RAM (7708.1 MB) (7.5 Gig)
Binutils Version:      2.24
Make Version in use:   4.0
Cmake Version in use:  3.0.2
CPU Model:             Intel(R) Celeron(R) CPU G1630 @ 2.80GHz
Screen Resolution:     1920x1080
Openssl Version:       1.0.1c
Tar Version:           1.28
Ruby Version:          2.1.3p242 (2014-09-19 revision 47630) [i686-linux]
Rubygems Version:      2.4.1
Rubygems Directory:    /Programs/Ruby/2.1.3/lib/ruby/gems/2.1.0
GTK Version 2:         2.24.22
GTK Version 3:         3.14.0
Glib Version:          2.42.0
ATK Version:           2.12.0
Pango Version:         1.36.8
Cairo Version:         1.12.16
Bison Version:         3.0.2
Intltool Version:      0.50.2
M4 Version:            1.4.17
Flex Version:          2.5.39
Readline Version:      6.3
File version:          5.11
KDE Version:           4.14.1
Grep Version:          2.20
Coreutils Version:     8.19
Fontconfig Version:    2.11.1
Perl Version:          5.16.1
Python Version:        2.7.8
Ffmpeg Version:        2.4
Find Version:          4.4.2
Gzip Version:          1.5
Sed Version:           4.2.2
Patch Version:         2.7.1
Nasm version:          2.11.05
Gcr version:           3.13.91

**Comment by ryanmelt** [comment]
My only guess here is that you have multiple versions of the Qt headers on your system and smoke is finding the wrong ones.
